### ISSUE TITLE
How to generate the syscall table

### ISSUE THREAD

**Issue by Phantom1003** [hrw/syscalls-table#13]
Hi, I wonder how to generate tables like you offer.  
I find that there are no standard format for different arch, like arm32 and x86 use *.tbl, while riscv use systable.c. Is there any  general method to get the syscall table of each arch ?

**Comment by hrw** [comment]
Check history of [grab_syscall_names_from_tables.sh](https://github.com/hrw/syscalls-table/blob/master/grab_syscall_names_from_tables.sh) script.

First it gathered list of system call names from include/asm/unistd.h file. Then tbl files were added for some archs and I started using them. Then more and more architectures switched to this format.

RISC-V is young architecture so it uses common list (same as few other archs) that's why they do not generate tbl file. Their list is in include/uapi/asm-generic/unistd.h file.

And as I only need a list of system calls then parsing tbl files is all I need nowadays. Which are supported and with which numbers is checked in next step.

I hope it answered your question.
